function gpcf=per_init(x,y,dim)
    % optional: dim is the dimension on which the se kernel is defined
    if size(x,2) > 1
        x = x(:,dim);
    end
    std_x = std(x);
    std_y = std(y);
    n=length(x);
    minp = log(10*(max(x)-min(x))/n);
    maxp = log((max(x)-min(x))/5);
    plper=prior_gaussian('mu',minp+1,'s2',0.25);
    plmaxper=prior_gaussian('mu',maxp-2,'s2',0.5);
    if nargin == 2
        if rand() < 0.5
            gpcf = gpcf_periodic('lengthScale',std_x*exp(randn()/2),...
            'period',exp(minp+TruncatedGaussian(-1/2,[0,Inf])),'magnSigma2',...
            0.1*std_y*exp(randn()/2),'lengthScale_prior',prior_t(),...
            'period_prior',plper);
        else
            gpcf = gpcf_periodic('lengthScale',std_x*exp(randn()/2),...
            'period',exp(maxp+TruncatedGaussian(1/2,[-Inf,0])),'magnSigma2',...
            0.1*std_y*exp(randn()/2),'lengthScale_prior',prior_t(),...
            'period_prior',plmaxper);
        end
    else
        if rand() < 0.5
            gpcf = gpcf_periodic('lengthScale',std_x*exp(randn()/2),...
            'period',exp(minp+TruncatedGaussian(-1/2,[0,Inf])),'magnSigma2',...
            0.1*std_y*exp(randn()/2),'lengthScale_prior',prior_t(),...
            'period_prior',plper,'selectedVariables',dim);
        else
            gpcf = gpcf_periodic('lengthScale',std_x*exp(randn()/2),...
            'period',exp(maxp+TruncatedGaussian(1/2,[-Inf,0])),'magnSigma2',...
            0.1*std_y*exp(randn()/2),'lengthScale_prior',prior_t(),...
            'period_prior',plmaxper,'selectedVariables',dim);
        end
    end
end